version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - run:
          name: "Install js dependencies"
          command: yarn
      - run:
          name: "Publish npm package"
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "Trying to publish package, if it fails then this verison has already been published."
              set +e
              npm publish .
              set -e
            else
              echo "Packages are only published to npm on branch 'master'."
            fi
            exit 0
